# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-17 13:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0438\u0434\u0435\u043e')),
                ('link', models.CharField(max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0438\u0434\u0435\u043e')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': '\u0423\u0440\u043e\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_type',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0443\u0440\u043e\u043a\u0430'),
            preserve_default=False,
        ),
    ]
