# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('check', models.CharField(blank=True, default='test', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0441\u0442',
                'verbose_name_plural': '\u0422\u0435\u0441\u0442\u044b \u0434\u043b\u044f \u0443\u0440\u043e\u043a\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u0442\u0435\u0441\u0442\u0430')),
                ('image', models.ImageField(upload_to='images/test', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0434\u043b\u044f \u0442\u0435\u0441\u0442\u0430')),
                ('true', models.BooleanField(verbose_name='\u0424\u0435\u0439\u043a')),
                ('false', models.BooleanField(verbose_name='\u041d\u0435 \u0424\u0435\u0439\u043a')),
                ('test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.LessonTest', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0442\u0435\u0441\u0442\u044b')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0441\u0442',
                'verbose_name_plural': '\u0422\u0435\u0441\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.ManyToManyField(blank=True, to='main.LessonTest', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0442\u0435\u0441\u0442'),
        ),
    ]
