# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170718_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name of slide')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='image')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Image',
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(default=1, upload_to='files/audio', verbose_name='audiofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='imageslide',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ImageSlide', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430'),
            preserve_default=False,
        ),
    ]
