# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170718_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='imageslide',
        ),
        migrations.AddField(
            model_name='lesson',
            name='imageslide',
            field=models.ManyToManyField(to='main.ImageSlide', verbose_name='slider image'),
        ),
    ]
